apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-sample
  name: spring-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-sample
    spec:
      containers:
      - image: paullee714/springboot-sample
        name: springboot-sample
        resources: {}
status: {}
